/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package growthbook.sdk.java;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Hello, world!");
        return true;
    }
}
