/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package growthbook.sdk.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GrowthBookTest {
    @Test void someLibraryMethodReturnsTrue() {
        GrowthBook classUnderTest = new GrowthBook();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
